name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7

    steps:
    - name: Code checkout
      uses: actions/checkout@v2.3.4

    - name: Build the Docker image
      uses: uraimo/run-on-arch-action@v2.0.5
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu18.04
        run: |
          docker build . --file Dockerfile --tag keretzlaff/venetian-blinds-2-mqtt:$(date +%s)
